<div style="text-align: center;margin-top: 50px">
    <ul id="slider">
        <li><iframe height=498 width=510 frameborder=0 src="http://player.youku.com/embed/XNDM4NDU5OTIw" allowfullscreen></iframe></li>
        
        <li><embed src="http://www.tudou.com/v/aC_0LYVYsx4/&resourceId=0_05_05_99&bid=05/v.swf" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" wmode="opaque" width="480" height="400"></embed></li>
        
        <li><iframe width="480" height="385" src="http://www.youtube.com/embed/9bZkp7q19f0" frameborder="0" allowfullscreen></iframe></li>
        
        <li><iframe width="480" height="385" src="http://www.youtube.com/embed/Ig6iX4sX1hA" frameborder="0" allowfullscreen></iframe></li>
<!--         Vimeo: iframe -->
        <li><iframe src="http://player.vimeo.com/video/18011143?title=0&amp;byline=0&amp;portrait=0" width="400" height="225" frameborder="0"></iframe></li>
        
        <li><embed src="http://www.tudou.com/v/dSLDOsBgSrA/&resourceId=0_05_02_99/v.swf" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" wmode="opaque" width="480" height="400"></embed></li>
<!--         Vimeo: Embeded -->
        <li><object width="940" height="529"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=12280336&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=00adef&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=12280336&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=00adef&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="940" height="529"></embed></object></li>
    </ul>
</div>
<div style="text-align: center;margin-top: 50px: ">
    <h1>站长的话:</h1>
    <p>为了更好的服务大家，减少使用障碍(譬如繁琐的注册过程，个人信息更新等)，本站长正在将服务接入<strong>新浪微博</strong></p>
    <p>在此期间，现有功能还能<strong style="color: red">继续使用</strong>，您依然可以选择注册，修改头像，并记录地图信息，但在正式接入微博前本站不再更新功能。</p>
    <p>与此同时，您可能会注意到一些微博元素，比如使用微博登录小工具，虽说没什么坏处，但请<strong style="color: red">暂时不要使用</strong></p>
    <p>谢谢</p>
</div>