<div>
    <div style="float: left;width: 20%">
        <h3>关注墙外道:</h3>
        <div>
            <img width="25" src="<?php echo $this->serverUrl() ?>/img/qq.png">84118706</img>
        </div>
        <div>
            <a href="https://twitter.com/WenjiangXu" class="twitter-follow-button" data-show-screen-name="false" data-show-count="true" data-lang="zh-cn">关注</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
        <div>
            <wb:follow-button uid="2017779583" type="red_3"></wb:follow-button>
        </div>
    </div>
    <div style="float: left;width: 40%">
        <div style="margin:auto;width:70%;">
            <img width="100%" src="<?php echo $this->serverUrl() ?>/img/me.jpg"></img>
        </div> 
    </div>
    <div style="float: left;width: 40%">
        <h1>关于我</h1>
        <p>这家伙很懒，什么都没有留下</p>
        <p>求人帮做前端。。。Orz。。。这页面太丑了。。。</p>
        <p>请给我发邮件: <a href="mailto:scac59414@gmail.com">scac59414@gmail.com</a><p>
    </div>
</div>